version: 2

jobs:
  bionic:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - checkout
      - run: apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4; echo "deb http://repo.yandex.ru/clickhouse/deb/stable/ main/" | tee /etc/apt/sources.list.d/clickhouse.list
      - run: apt-get update; DEBIAN_FRONTEND=noninteractive apt-get install -y clickhouse-server
      - run: openssl req -subj "/CN=my.host.name" -days 365 -nodes -new -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt
      - run: openssl dhparam -out /etc/clickhouse-server/dhparam.pem 1024
      - run: echo .circleci/clickhouse.config.xml > /etc/clickhouse-server/config.xml
      - run: chown -R clickhouse:clickhouse /etc/clickhouse-server/
      - run: service clickhouse-server start
      - run: swift build --enable-test-discovery
      - run: CLICKHOUSE_SERVER="127.0.0.1" CLICKHOUSE_USER="default" CLICKHOUSE_PASSWORD="" swift test --enable-test-discovery
      
workflows:
  version: 2
  tests:
    jobs:
      - bionic